/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VsBotRouteImport } from './routes/vs-bot'
import { Route as VsAiRouteImport } from './routes/vs-ai'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OnlineMatchRouteImport } from './routes/online-match'
import { Route as MultiplayerRouteImport } from './routes/multiplayer'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayLevelRouteImport } from './routes/play.$level'

const VsBotRoute = VsBotRouteImport.update({
  id: '/vs-bot',
  path: '/vs-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const VsAiRoute = VsAiRouteImport.update({
  id: '/vs-ai',
  path: '/vs-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineMatchRoute = OnlineMatchRouteImport.update({
  id: '/online-match',
  path: '/online-match',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerRoute = MultiplayerRouteImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLevelRoute = PlayLevelRouteImport.update({
  id: '/play/$level',
  path: '/play/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-to-play': typeof HowToPlayRoute
  '/levels': typeof LevelsRoute
  '/multiplayer': typeof MultiplayerRoute
  '/online-match': typeof OnlineMatchRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/rewards': typeof RewardsRoute
  '/vs-ai': typeof VsAiRoute
  '/vs-bot': typeof VsBotRoute
  '/play/$level': typeof PlayLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-to-play': typeof HowToPlayRoute
  '/levels': typeof LevelsRoute
  '/multiplayer': typeof MultiplayerRoute
  '/online-match': typeof OnlineMatchRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/rewards': typeof RewardsRoute
  '/vs-ai': typeof VsAiRoute
  '/vs-bot': typeof VsBotRoute
  '/play/$level': typeof PlayLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-to-play': typeof HowToPlayRoute
  '/levels': typeof LevelsRoute
  '/multiplayer': typeof MultiplayerRoute
  '/online-match': typeof OnlineMatchRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/rewards': typeof RewardsRoute
  '/vs-ai': typeof VsAiRoute
  '/vs-bot': typeof VsBotRoute
  '/play/$level': typeof PlayLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/how-to-play'
    | '/levels'
    | '/multiplayer'
    | '/online-match'
    | '/premium'
    | '/privacy'
    | '/rewards'
    | '/vs-ai'
    | '/vs-bot'
    | '/play/$level'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/how-to-play'
    | '/levels'
    | '/multiplayer'
    | '/online-match'
    | '/premium'
    | '/privacy'
    | '/rewards'
    | '/vs-ai'
    | '/vs-bot'
    | '/play/$level'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/how-to-play'
    | '/levels'
    | '/multiplayer'
    | '/online-match'
    | '/premium'
    | '/privacy'
    | '/rewards'
    | '/vs-ai'
    | '/vs-bot'
    | '/play/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HowToPlayRoute: typeof HowToPlayRoute
  LevelsRoute: typeof LevelsRoute
  MultiplayerRoute: typeof MultiplayerRoute
  OnlineMatchRoute: typeof OnlineMatchRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  RewardsRoute: typeof RewardsRoute
  VsAiRoute: typeof VsAiRoute
  VsBotRoute: typeof VsBotRoute
  PlayLevelRoute: typeof PlayLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vs-bot': {
      id: '/vs-bot'
      path: '/vs-bot'
      fullPath: '/vs-bot'
      preLoaderRoute: typeof VsBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs-ai': {
      id: '/vs-ai'
      path: '/vs-ai'
      fullPath: '/vs-ai'
      preLoaderRoute: typeof VsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-match': {
      id: '/online-match'
      path: '/online-match'
      fullPath: '/online-match'
      preLoaderRoute: typeof OnlineMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer': {
      id: '/multiplayer'
      path: '/multiplayer'
      fullPath: '/multiplayer'
      preLoaderRoute: typeof MultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$level': {
      id: '/play/$level'
      path: '/play/$level'
      fullPath: '/play/$level'
      preLoaderRoute: typeof PlayLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HowToPlayRoute: HowToPlayRoute,
  LevelsRoute: LevelsRoute,
  MultiplayerRoute: MultiplayerRoute,
  OnlineMatchRoute: OnlineMatchRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  RewardsRoute: RewardsRoute,
  VsAiRoute: VsAiRoute,
  VsBotRoute: VsBotRoute,
  PlayLevelRoute: PlayLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
