/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VsBotRouteImport } from './routes/vs-bot'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as MultiplayerRouteImport } from './routes/multiplayer'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayLevelRouteImport } from './routes/play.$level'

const VsBotRoute = VsBotRouteImport.update({
  id: '/vs-bot',
  path: '/vs-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerRoute = MultiplayerRouteImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLevelRoute = PlayLevelRouteImport.update({
  id: '/play/$level',
  path: '/play/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/levels': typeof LevelsRoute
  '/multiplayer': typeof MultiplayerRoute
  '/rewards': typeof RewardsRoute
  '/vs-bot': typeof VsBotRoute
  '/play/$level': typeof PlayLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/levels': typeof LevelsRoute
  '/multiplayer': typeof MultiplayerRoute
  '/rewards': typeof RewardsRoute
  '/vs-bot': typeof VsBotRoute
  '/play/$level': typeof PlayLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/levels': typeof LevelsRoute
  '/multiplayer': typeof MultiplayerRoute
  '/rewards': typeof RewardsRoute
  '/vs-bot': typeof VsBotRoute
  '/play/$level': typeof PlayLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/levels'
    | '/multiplayer'
    | '/rewards'
    | '/vs-bot'
    | '/play/$level'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/levels' | '/multiplayer' | '/rewards' | '/vs-bot' | '/play/$level'
  id:
    | '__root__'
    | '/'
    | '/levels'
    | '/multiplayer'
    | '/rewards'
    | '/vs-bot'
    | '/play/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LevelsRoute: typeof LevelsRoute
  MultiplayerRoute: typeof MultiplayerRoute
  RewardsRoute: typeof RewardsRoute
  VsBotRoute: typeof VsBotRoute
  PlayLevelRoute: typeof PlayLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vs-bot': {
      id: '/vs-bot'
      path: '/vs-bot'
      fullPath: '/vs-bot'
      preLoaderRoute: typeof VsBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer': {
      id: '/multiplayer'
      path: '/multiplayer'
      fullPath: '/multiplayer'
      preLoaderRoute: typeof MultiplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$level': {
      id: '/play/$level'
      path: '/play/$level'
      fullPath: '/play/$level'
      preLoaderRoute: typeof PlayLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LevelsRoute: LevelsRoute,
  MultiplayerRoute: MultiplayerRoute,
  RewardsRoute: RewardsRoute,
  VsBotRoute: VsBotRoute,
  PlayLevelRoute: PlayLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
